package_update: true

bootcmd:
    - systemctl enable snapd

snap:
    commands:
        - snap install maas --channel=latest/edge
        - snap install maas-test-db --channel=latest/edge

runcmd:
    - export CHANNEL="latest/edge"
    - export MAAS_URL="http://localhost:5240/MAAS"
    - export MAASDB_DUMP_URL="https://github.com/canonical/maas-ui-testing/raw/main/db/maasdb-22.04-master-100.dump"

    - |
        echo "Setting up MAAS with database dump..."
        set -x

        # Fetch MAAS database dump
        wget -O /tmp/maasdb.dump "$MAASDB_DUMP_URL"

        # Configure PostgreSQL
        sed -i "s/dynamic_shared_memory_type = posix/dynamic_shared_memory_type = sysv/" /var/snap/maas-test-db/common/postgres/data/postgresql.conf

        # Restart maas-test-db
        snap restart maas-test-db

        # Wait for service to be ready
        sleep 10

        # Move database dump
        mv /tmp/maasdb.dump /var/snap/maas-test-db/common/maasdb.dump

        # Restore database
        snap run --shell maas-test-db.psql -c 'db-dump restore /var/snap/maas-test-db/common/maasdb.dump maassampledata'

        # Initialize MAAS with database
        maas init region+rack --maas-url="$MAAS_URL" --database-uri maas-test-db:///

        # Update database configuration
        sed -i "s/database_name: maasdb/database_name: maassampledata/" /var/snap/maas/current/regiond.conf

        # Restart MAAS
        snap restart maas

        echo "MAAS setup with database dump completed"
