version: "3.8"

services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./static/index.html:/usr/share/nginx/html/index.html:ro
        depends_on:
            - session-manager
            - maas-frontend
            - app2-frontend
        networks:
            - demo-network

    session-manager:
        build: ./session-manager
        expose:
            - "8080"
        networks:
            - demo-network

    build-manager:
        build: ./build-manager
        ports:
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/docker-compose:ro
        networks:
            - demo-network
        depends_on:
            - session-manager
            - maas-frontend
            - app2-frontend

    maas-frontend:
        build: ./applications/maas/frontend
        expose:
            - "80"
        networks:
            - demo-network

    app2-frontend:
        image: nginx:alpine
        volumes:
            - ./static/app2:/usr/share/nginx/html:ro
        expose:
            - "80"
        networks:
            - demo-network

networks:
    demo-network:
        driver: bridge
